site_name: 工作笔记
pages:
  - 主页: index.md
  - C++: 
     - 模拟代码逻辑: C++/logiccode.md
     - 代码块: C++/blockcode.md
     - 常用代码: C++/commoncode.md
     - 系统代码块: C++/syscode.md
     - 配置读取: C++/configcode.md
     - RMI远程方法调用: C++/rmicode.md
  - vim:
     - 字符串搜索替换: Vim/replace.md
     - 文件分屏显示操作: Vim/editfiles.md
  - gdb:
     - 常用命令: gdb/gdb.md
  - sql:
     - Mysql: Sql/mysql.md
  - shell:
     - 常用Shell命令: Linux/common_shell.md
  - gm:
     - 常用Gm命令: gm.md
  - 杂项:
     - 其他: other.md

theme:
  name: 'material'
  logo:
    icon: 'school'
  palette:
    primary: 'blue grey'
    accent: 'light blue'
  font:
    text: 'Open Sans'
    code: 'Open Sans Mono'
  language: 'zh'

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.mark

repo_url: https://lablelan.github.io/WorkNote
edit_uri: ""