site_name: 工作笔记
pages:
  - 主页: index.md
  - C++: 
     - 代码逻辑: C++/logiccode.md
  - vim:
     - 字符串搜索替换: Vim/replace.md
  - gdb:
     - 常用命令: gdb/gdb.md
  - sql:
     - Mysql: Sql/mysql.md
  - shell:
     - 常用Shell命令: Linux/common_shell.md

theme:
  name: 'material'
  logo:
    icon: 'school'
  palette:
    primary: 'blue grey'
    accent: 'light blue'
  font:
    text: 'Open Sans'
    code: 'Open Sans Mono'
  language: 'zh'

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.mark

repo_url: https://lablelan.github.io/WorkNote
edit_uri: ""